/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const SubsectionItem = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Subsection = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'items' : IDL.Vec(SubsectionItem),
});
export const Infographic = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'graphic' : ExternalBlob,
});
export const Section = IDL.Record({
  'title' : IDL.Text,
  'subsections' : IDL.Vec(Subsection),
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'infographic' : IDL.Opt(Infographic),
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'whatsappConfirmed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'isVaishnav' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isJain' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const OrderType = IDL.Variant({
  'cart' : IDL.Record({ 'items' : IDL.Vec(MenuItem) }),
  'singleItem' : MenuItem,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'deliveryCharge' : IDL.Float64,
  'total' : IDL.Float64,
  'orderType' : OrderType,
  'whatsappNumber' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Time,
  'upiId' : IDL.Text,
  'deliveryDistanceKm' : IDL.Float64,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'review' : IDL.Text,
  'from' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const DeploymentStatus = IDL.Record({
  'verified' : IDL.Bool,
  'canisterURL' : IDL.Text,
  'dnsInstructions' : IDL.Text,
  'isPermanent' : IDL.Bool,
});
export const MenuCategory = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'items' : IDL.Vec(MenuItem),
});
export const DetailedMenu = IDL.Record({
  'categories' : IDL.Vec(MenuCategory),
  'sections' : IDL.Vec(Section),
});
export const PromotionalMaterial = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'file' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmUpiPayment' : IDL.Func([IDL.Nat], [], []),
  'downloadMenuPDF' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllMenuSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeploymentStatus' : IDL.Func([], [DeploymentStatus], ['query']),
  'getDetailedMenu' : IDL.Func([], [DetailedMenu], ['query']),
  'getLogo' : IDL.Func([], [IDL.Opt(PromotionalMaterial)], ['query']),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
  'getMenuCategory' : IDL.Func([IDL.Text], [IDL.Opt(MenuCategory)], ['query']),
  'getMenuSection' : IDL.Func([IDL.Text], [IDL.Opt(Section)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getPermanentCanisterURL' : IDL.Func([], [IDL.Text], ['query']),
  'getPromoMaterial' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PromotionalMaterial)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [OrderType, IDL.Float64, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateLogo' : IDL.Func([ExternalBlob], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'uploadPromoMaterial' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const SubsectionItem = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Subsection = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'items' : IDL.Vec(SubsectionItem),
  });
  const Infographic = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'graphic' : ExternalBlob,
  });
  const Section = IDL.Record({
    'title' : IDL.Text,
    'subsections' : IDL.Vec(Subsection),
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'infographic' : IDL.Opt(Infographic),
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'whatsappConfirmed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'isVaishnav' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isJain' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const OrderType = IDL.Variant({
    'cart' : IDL.Record({ 'items' : IDL.Vec(MenuItem) }),
    'singleItem' : MenuItem,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'deliveryCharge' : IDL.Float64,
    'total' : IDL.Float64,
    'orderType' : OrderType,
    'whatsappNumber' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Time,
    'upiId' : IDL.Text,
    'deliveryDistanceKm' : IDL.Float64,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'review' : IDL.Text,
    'from' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DeploymentStatus = IDL.Record({
    'verified' : IDL.Bool,
    'canisterURL' : IDL.Text,
    'dnsInstructions' : IDL.Text,
    'isPermanent' : IDL.Bool,
  });
  const MenuCategory = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'items' : IDL.Vec(MenuItem),
  });
  const DetailedMenu = IDL.Record({
    'categories' : IDL.Vec(MenuCategory),
    'sections' : IDL.Vec(Section),
  });
  const PromotionalMaterial = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'file' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmUpiPayment' : IDL.Func([IDL.Nat], [], []),
    'downloadMenuPDF' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllMenuSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeploymentStatus' : IDL.Func([], [DeploymentStatus], ['query']),
    'getDetailedMenu' : IDL.Func([], [DetailedMenu], ['query']),
    'getLogo' : IDL.Func([], [IDL.Opt(PromotionalMaterial)], ['query']),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
    'getMenuCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MenuCategory)],
        ['query'],
      ),
    'getMenuSection' : IDL.Func([IDL.Text], [IDL.Opt(Section)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getPermanentCanisterURL' : IDL.Func([], [IDL.Text], ['query']),
    'getPromoMaterial' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PromotionalMaterial)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [OrderType, IDL.Float64, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateLogo' : IDL.Func([ExternalBlob], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'uploadPromoMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };