/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface DeploymentStatus {
  'verified' : boolean,
  'canisterURL' : string,
  'dnsInstructions' : string,
  'isPermanent' : boolean,
}
export interface DetailedMenu {
  'categories' : Array<MenuCategory>,
  'sections' : Array<Section>,
}
export type ExternalBlob = Uint8Array;
export interface Infographic {
  'title' : string,
  'icon' : string,
  'description' : string,
  'graphic' : ExternalBlob,
}
export interface MenuCategory {
  'id' : string,
  'name' : string,
  'description' : string,
  'items' : Array<MenuItem>,
}
export interface MenuItem {
  'isVaishnav' : boolean,
  'name' : string,
  'description' : string,
  'isJain' : boolean,
  'category' : string,
  'price' : number,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'deliveryCharge' : number,
  'total' : number,
  'orderType' : OrderType,
  'whatsappNumber' : string,
  'address' : string,
  'timestamp' : Time,
  'upiId' : string,
  'deliveryDistanceKm' : number,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'whatsappConfirmed' : null } |
  { 'confirmed' : null };
export type OrderType = { 'cart' : { 'items' : Array<MenuItem> } } |
  { 'singleItem' : MenuItem };
export interface PromotionalMaterial {
  'id' : string,
  'title' : string,
  'file' : ExternalBlob,
}
export interface Section {
  'title' : string,
  'subsections' : Array<Subsection>,
  'icon' : string,
  'description' : string,
  'infographic' : [] | [Infographic],
}
export interface Subsection {
  'title' : string,
  'content' : string,
  'items' : Array<SubsectionItem>,
}
export interface SubsectionItem { 'title' : string, 'description' : string }
export interface Testimonial {
  'id' : bigint,
  'review' : string,
  'from' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTestimonial' : ActorMethod<[string, string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmUpiPayment' : ActorMethod<[bigint], undefined>,
  'downloadMenuPDF' : ActorMethod<[], [] | [ExternalBlob]>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllMenuSections' : ActorMethod<[], Array<Section>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeploymentStatus' : ActorMethod<[], DeploymentStatus>,
  'getDetailedMenu' : ActorMethod<[], DetailedMenu>,
  'getLogo' : ActorMethod<[], [] | [PromotionalMaterial]>,
  'getMenu' : ActorMethod<[], Array<MenuCategory>>,
  'getMenuCategory' : ActorMethod<[string], [] | [MenuCategory]>,
  'getMenuSection' : ActorMethod<[string], [] | [Section]>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getPermanentCanisterURL' : ActorMethod<[], string>,
  'getPromoMaterial' : ActorMethod<[string], [] | [PromotionalMaterial]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importTestimonial' : ActorMethod<[string, string, bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[OrderType, number, string, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateLogo' : ActorMethod<[ExternalBlob], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'uploadPromoMaterial' : ActorMethod<
    [string, string, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];